#!/bin/bash
# merge_constants.sh - Create single source of truth for all constants

cd /mnt/data1/nix/vendor/rust/github/data/proofs

echo "🔧 Merging all constants into single file..."

OUT="generated/merged_constants.pl"

cat > "$OUT" << 'EOF'
% merged_constants.pl - Single source of truth for ALL constants
% Generated by merge_constants.sh
% DO NOT EDIT - This is auto-generated

% ═══════════════════════════════════════════════════════════
% MONSTER PRIMES (20 primes from Monster group)
% ═══════════════════════════════════════════════════════════

monster_primes([2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71]).

monster_prime(2).
monster_prime(3).
monster_prime(5).
monster_prime(7).
monster_prime(11).
monster_prime(13).
monster_prime(17).
monster_prime(19).
monster_prime(23).
monster_prime(29).
monster_prime(31).
monster_prime(37).
monster_prime(41).
monster_prime(43).
monster_prime(47).
monster_prime(53).
monster_prime(59).
monster_prime(61).
monster_prime(67).
monster_prime(71).

% ═══════════════════════════════════════════════════════════
% EMOJI MAPPINGS (Prime → Emoji)
% ═══════════════════════════════════════════════════════════

emoji_prime(2, '🌊').
emoji_prime(3, '🔺').
emoji_prime(5, '⭐').
emoji_prime(7, '🌈').
emoji_prime(11, '🎯').
emoji_prime(13, '🔮').
emoji_prime(17, '⚡').
emoji_prime(19, '🌙').
emoji_prime(23, '🎨').
emoji_prime(29, '🎭').
emoji_prime(31, '🎪').
emoji_prime(37, '🎬').
emoji_prime(41, '🎮').
emoji_prime(43, '🎲').
emoji_prime(47, '🎰').
emoji_prime(53, '🎸').
emoji_prime(59, '🎺').
emoji_prime(61, '🎻').
emoji_prime(67, '🎼').
emoji_prime(71, '🎵').

% ═══════════════════════════════════════════════════════════
% PATHS (Canonical locations)
% ═══════════════════════════════════════════════════════════

meta_parquet_path('/mnt/data1/time2/time/2023/07/30/meta-meme/plocate_witness/lists_of_lists.parquet').
locate_digest_path('/mnt/data1/time2/time/2023/07/30/meta-meme/plocate_witness/locate_digest.parquet').
meta_meta_path('/mnt/data1/time2/time/2023/07/30/meta-meme/plocate_witness/meta_meta_structures.parquet').

generated_path('data/proofs/generated').
repos_path('data/proofs/repos').

% ═══════════════════════════════════════════════════════════
% GÖDEL ENCODING (Type → Prime)
% ═══════════════════════════════════════════════════════════

type_prime(file, 2).
type_prime(function, 3).
type_prime(fact, 5).
type_prime(proof, 7).
type_prime(parquet, 11).
type_prime(repo, 13).
type_prime(module, 17).
type_prime(struct, 19).
type_prime(enum, 23).
type_prime(trait, 29).
type_prime(impl, 31).
type_prime(const, 37).
type_prime(static, 41).
type_prime(fn, 43).
type_prime(macro, 47).
type_prime(type, 53).
type_prime(use, 59).
type_prime(mod, 61).
type_prime(pub, 67).
type_prime(crate, 71).

% ═══════════════════════════════════════════════════════════
% UNIVERSE LEVELS (Schema hierarchy)
% ═══════════════════════════════════════════════════════════

universe_level(0, table).      % Base tables
universe_level(1, meta).       % Meta-tables
universe_level(2, meta_meta).  % Meta-meta
universe_level(71, universe).  % Top level

% ═══════════════════════════════════════════════════════════
% COMPLEXITY SOURCES
% ═══════════════════════════════════════════════════════════

complexity_source(oeis, 'https://oeis.org').
complexity_source(monster, 'Monster group').
complexity_source(hecke, 'Hecke operators').
complexity_source(galois, 'Galois theory').

% ═══════════════════════════════════════════════════════════
% HELPER PREDICATES
% ═══════════════════════════════════════════════════════════

% Check if prime is Monster prime
is_monster_prime(P) :- monster_prime(P).

% Get emoji for prime
prime_emoji(P, E) :- emoji_prime(P, E).

% Get prime for type
type_to_prime(T, P) :- type_prime(T, P).

% Gödel encode: multiply primes
godel_encode([], 1).
godel_encode([P|Ps], G) :-
    godel_encode(Ps, G0),
    G is P * G0.

% ═══════════════════════════════════════════════════════════
% END OF MERGED CONSTANTS
% ═══════════════════════════════════════════════════════════
EOF

echo "✅ Created $OUT"

# Count lines
LINES=$(wc -l < "$OUT")
echo "  Lines: $LINES"

# Show what we merged
echo
echo "📊 MERGED:"
echo "  20 Monster primes"
echo "  20 Emoji mappings"
echo "  5 Canonical paths"
echo "  20 Type→Prime mappings"
echo "  4 Universe levels"
echo "  4 Complexity sources"
echo
echo "✅ All constants now in ONE file: $OUT"
